### ISSUE TITLE
Implement end of life function

### ISSUE THREAD

**Issue by MikeL9286** [Pondidum/NScientist#1]
To make it cleaner for projects that use feature toggles, users should be able to set an 'end of life' function that, when true, bypasses the experiment and exclusively uses the TRY function. 

BEFORE
```
if (featureEnabled) return trialFunc;

return = Experiment
.On(controlFunc)
.Try(trialFunc)
.Run();
```

AFTER
```
return = Experiment
.On(controlFunc)
.Try(trialFunc)
.EndOfLife(featureEnabled)
.Run();
```

**Comment by Pondidum** [comment]
Resolved with #2
